# 🗄️ DATABASE (Supabase / PostgreSQL)
spring.datasource.url=jdbc:postgresql://db.zblqepstaufycdrmrfda.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=.Zetazetaoakvc95

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ☁️ SUPABASE STORAGE CONFIG
supabase.url=https://YOUR_SUPABASE_PROJECT.supabase.co
supabase.bucket=uploads
supabase.apiKey=YOUR_SUPABASE_SERVICE_ROLE_KEY

# 🔐 JWT Secret
jwt.secret=YOUR_JWT_SECRET_KEY
jwt.expiration=86400000